server:
  port: 8080

spring:
  application:
    name: register-center

  datasource:
    url: jdbc:mysql://101.34.66.53:3306/bandaotiehe
    username: bandaotiehe
    password: fC6Zw5zJMEP4Tst3
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    type: com.alibaba.druid.pool.DruidDataSource

  logging:
    level:
      root: info
      com.szyciov: debug

mybatis:
  mapper-locations: classpath:mappers/*.xml